[phases.setup]
nixPkgs = ['gcc', 'python39', 'postgresql', 'pip']

[phases.install]
cmds = [

]

[phases.build]
cmds = [

]



[build.args]
PYTHON_VERSION = "3.9"

[build.environment]
PYTHONUNBUFFERED = "1"
PYTHONPATH = "."
ENVIRONMENT = "production"
